<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ot_website"
 *
 * Auto generated by Extension Builder 2014-06-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Website',
	'description' => 'Descr.',
	'category' => 'templates',
	'author' => 'Oliver Thiele',
	'author_email' => 'mailYYYY@oliver-thiele.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'dividers2tabs' => TRUE,
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
